name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - name: Build binaries
        run: |
          # Create dist directory
          mkdir -p dist
          
          # Build for different platforms
          GOOS=linux GOARCH=amd64 go build -o dist/gmail-label-fixer-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o dist/gmail-label-fixer-linux-arm64
          GOOS=darwin GOARCH=amd64 go build -o dist/gmail-label-fixer-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o dist/gmail-label-fixer-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -o dist/gmail-label-fixer-windows-amd64.exe
          GOOS=windows GOARCH=arm64 go build -o dist/gmail-label-fixer-windows-arm64.exe
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/gmail-label-fixer-*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}